name: ci
on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Run checks
      run: |
        go mod tidy && git diff --no-patch --exit-code
        go mod download
        make coverage
        make lint
        make dev
